import type { StyleSheet } from './types';

export const styleSheet: StyleSheet = {
  ".s-hero": {
    "position": "relative",
  },
  ".hero-front": {
    "display": "grid",
    "grid-template-columns": "minmax(0, 0.95fr) minmax(340px, 0.9fr)",
    "align-items": "center",
    "min-height": "100svh",
    "gap": "clamp(1.5rem, 5vw, 5rem)",
    "position": "relative",
  },
  ".hero-copy": {
    "position": "relative",
    "z-index": "3",
    "display": "flex",
    "flex-direction": "column",
    "align-items": "flex-start",
    "justify-content": "center",
    "max-width": "760px",
    "padding-left": "clamp(0rem, 1.8vw, 1.2rem)",
    "margin-top": "clamp(0rem, 1.5vh, 1rem)",
  },
  ".hero-visual": {
    "position": "absolute",
    "z-index": "2",
    "right": "clamp(0rem, 2vw, 1.5rem)",
    "top": "clamp(8%, 10vh, 14%)",
    "bottom": "clamp(8%, 10vh, 14%)",
    "width": "min(44vw, 620px)",
    "display": "flex",
    "align-items": "flex-end",
    "justify-content": "center",
  },
  ".hero-greeting": {
    "margin": "0",
    "color": "#f0abfc",
    "font-weight": "600",
    "font-size": "clamp(1.02rem, 1.2vw, 1.2rem)",
    "letter-spacing": "0.08em",
    "text-transform": "uppercase",
  },
  ".hero-name-block": {
    "margin": "0.9rem 0 0",
    "display": "flex",
    "flex-direction": "column",
    "gap": "0.08em",
    "font-size": "clamp(3rem, 7.4vw, 6.6rem)",
    "line-height": "0.94",
    "letter-spacing": "-0.05em",
    "font-weight": "700",
    "color": "#f8fbff",
    "text-wrap": "balance",
  },
  ".hero-name-line": {
    "display": "block",
  },
  ".hero-role-block": {
    "margin-top": "clamp(1.4rem, 2.2vw, 2rem)",
    "padding-top": "0",
    "width": "min(100%, 560px)",
  },
  ".hero-scroll-cue": {
    "position": "absolute",
    "left": "50%",
    "bottom": "clamp(3rem, 6vw, 4.8rem)",
    "transform": "translateX(-50%)",
    "z-index": "3",
    "display": "flex",
    "flex-direction": "column",
    "align-items": "center",
    "gap": "0.55rem",
    "pointer-events": "none",
    "animation": "scroll-cue-float 2.4s ease-in-out infinite",
  },
  ".hero-scroll-cue-shell": {
    "position": "relative",
    "display": "block",
    "width": "24px",
    "height": "38px",
    "border-radius": "999px",
    "border": "1px solid rgba(240, 171, 252, 0.65)",
    "background": "linear-gradient(180deg, rgba(255, 255, 255, 0.04), rgba(255, 255, 255, 0.01))",
    "box-shadow": "0 0 22px rgba(168, 85, 247, 0.16)",
  },
  ".hero-scroll-cue-dot": {
    "position": "absolute",
    "left": "50%",
    "top": "7px",
    "width": "4px",
    "height": "8px",
    "margin-left": "-2px",
    "border-radius": "999px",
    "background": "#f0abfc",
    "box-shadow": "0 0 10px rgba(240, 171, 252, 0.45)",
    "animation": "scroll-cue-dot 1.8s ease-in-out infinite",
  },
  ".hero-scroll-cue-text": {
    "font-size": "0.72rem",
    "letter-spacing": "0.22em",
    "text-transform": "uppercase",
    "color": "rgba(240, 171, 252, 0.82)",
  },
  "@media (max-width: 1024px)": {
    ".hero-front": {
      "grid-template-columns": "1fr",
    },
    ".hero-visual": {
      "position": "relative",
      "right": "auto",
      "top": "auto",
      "bottom": "auto",
      "justify-self": "center",
      "width": "min(100%, 520px)",
      "height": "min(52svh, 520px)",
    },
  },
};
