import type { StyleSheet } from './types';

export const styleSheet: StyleSheet = {
  ".hero-nav": {
    "position": "fixed",
    "top": "0",
    "left": "0",
    "width": "100%",
    "z-index": "12",
    "padding": "1.5rem 2rem",
    "background": "transparent",
    "pointer-events": "none",
  },
  ".hero-nav-inner": {
    "width": "100%",
    "margin": "0",
    "position": "relative",
    "display": "flex",
    "justify-content": "flex-end",
    "align-items": "center",
  },
  ".hero-nav-email": {
    "position": "absolute",
    "left": "50%",
    "transform": "translateX(-50%)",
    "color": "#ffffff",
    "text-decoration": "none",
    "font-size": "1rem",
    "font-weight": "600",
    "letter-spacing": "0.08em",
    "line-height": "1.1",
    "text-shadow": "0 0 12px rgba(255, 255, 255, 0.35), 0 0 20px rgba(168, 85, 247, 0.26)",
    "transition": "color 220ms ease, text-shadow 220ms ease",
    "pointer-events": "auto",
  },
  ".hero-nav-email:hover,\n.hero-nav-email:focus-visible": {
    "color": "#d8b4fe",
    "text-shadow": "0 0 14px rgba(216, 180, 254, 0.45)",
  },
  ".hero-nav-links": {
    "justify-self": "end",
    "display": "flex",
    "justify-content": "flex-end",
    "gap": "1.7rem",
    "font-weight": "600",
    "letter-spacing": "0.08em",
    "font-size": "1rem",
    "pointer-events": "auto",
  },
  ".hero-nav-links a": {
    "position": "relative",
    "display": "inline-grid",
    "place-items": "center",
    "overflow": "hidden",
    "height": "1.25em",
    "line-height": "1.1",
    "text-decoration": "none",
    "color": "#ffffff",
  },
  ".hero-nav-links .nav-label": {
    "grid-area": "1 / 1",
    "display": "inline-block",
    "will-change": "transform, opacity, color",
    "transition": "transform 460ms cubic-bezier(0.22, 1, 0.36, 1),\n    opacity 460ms cubic-bezier(0.22, 1, 0.36, 1),\n    color 320ms ease",
  },
};
