import type { StyleSheet } from './types';

export const styleSheet: StyleSheet = {
  ".social-dock": {
    "position": "fixed",
    "inset": "auto auto 1.35rem 1.35rem",
    "left": "1.35rem",
    "right": "auto",
    "top": "auto",
    "bottom": "1.35rem",
    "transform": "none",
    "z-index": "80",
    "display": "flex",
    "flex-direction": "column",
    "align-items": "flex-start",
    "gap": "0.9rem",
    "pointer-events": "auto",
    "opacity": "0",
    "will-change": "opacity",
    "transition": "opacity 680ms cubic-bezier(0.22, 1, 0.36, 1)",
  },
  ".social-dock a": {
    "position": "relative",
    "color": "#ffffff",
    "text-decoration": "none",
    "display": "grid",
    "place-items": "center",
    "width": "2.6rem",
    "height": "2.6rem",
    "border-radius": "999px",
    "border": "1px solid rgba(255, 255, 255, 0.16)",
    "background": "rgba(8, 5, 15, 0.42)",
    "isolation": "isolate",
    "transition": "color 260ms ease, transform 320ms cubic-bezier(0.22, 1, 0.36, 1)",
  },
  ".social-dock a::before,\n.social-dock a::after": {
    "content": "''",
    "position": "absolute",
    "inset": "0",
    "border-radius": "inherit",
    "pointer-events": "none",
    "opacity": "0",
    "transition": "opacity 260ms ease, transform 320ms cubic-bezier(0.22, 1, 0.36, 1)",
  },
  ".social-dock a::before": {
    "background": "linear-gradient(140deg, rgba(236, 72, 153, 0.95), rgba(168, 85, 247, 0.92))",
    "box-shadow": "0 0 18px rgba(236, 72, 153, 0.65),\n    0 0 30px rgba(168, 85, 247, 0.68),\n    0 0 48px rgba(168, 85, 247, 0.52)",
    "transform": "scale(0.76)",
  },
  ".social-dock a::after": {
    "inset": "-6px",
    "background": "radial-gradient(circle, rgba(192, 132, 252, 0.55), rgba(236, 72, 153, 0))",
    "filter": "blur(10px)",
    "transform": "scale(0.82)",
  },
  ".social-dock.is-visible": {
    "opacity": "1",
  },
  ".social-dock.is-hidden": {
    "pointer-events": "none",
  },
};
