export function getCountryCode(name: string) {
  const map: Record<string, string> = {
    "United Arab Emirates": "AE",
    "Australia": "AU",
    "Austria": "AT",
    "Belgium": "BE",
    "Canada": "CA",
    "Switzerland": "CH",
    "Croatia": "HR",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Germany": "DE",
    "Denmark": "DK",
    "Estonia": "EE",
    "Spain": "ES",
    "Finland": "FI",
    "France": "FR",
    "United Kingdom": "GB",
    "Greece": "GR",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "Ireland": "IE",
    "Israel": "IL",
    "India": "IN",
    "Indonesia": "ID",
    "Italy": "IT",
    "Japan": "JP",
    "South Korea": "KR",
    "Lithuania": "LT",
    "Latvia": "LV",
    "Luxembourg": "LU",
    "Malaysia": "MY",
    "Malta": "MT",
    "Mexico": "MX",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Norway": "NO",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Sweden": "SE",
    "Taiwan": "TW",
    "Thailand": "TH",
    "Turkey": "TR",
    "United States": "US",
    "Vietnam": "VN",
  };
  return map[name] || name; // fallback to input if already a code
}
